### ISSUE TITLE
Add check to see if ISLANDORA_REST_DATASTREAM_GET_PERM is defined

### ISSUE THREAD

**Issue by mjordan** [SFULibrary/islandora_context#24]
If islandora_rest isn't enabled, we get errors.

**Comment by mjordan** [comment]
Fix currently undergoing testing.

**Comment by MarcusBarnes** [comment]
@mjordan Would I be able to help test?  I know someone who is testing islandora_context and they are seeing this issue.  It would be great if it could be resolved.  Thanks.

**Comment by mjordan** [comment]
@MarcusBarnes yes, that would be great. I'll push up a branch with a fix after I do some additional testing on my end.

In the short term, as a workaround for this, they could install the [Islandora REST module](https://github.com/discoverygarden/islandora_rest), which defines ISLANDORA_REST_DATASTREAM_GET_PERM.

**Comment by mjordan** [comment]
@MarcusBarnes fix is in the issue-24 branch, ready to test. To do that:
1. Create a Context with a condition, say PID Namespace (any condition will do).
2. Add to this Context the reaction Users IP Address, and configure an IP range that does not include the IP that you are testing from (i.e., you want to be denied access during this test).
3. Save the Context.
4. Attempt to access an object that triggers your condition.

If Islandora REST is not installed, you should see no errors and you should be denied access to the object with the namespace configured in your Context condition.

If you want to test with Islandora REST enabled, install and enable that module, and then from a computer that is outside your configured IP range, issue the following command:

`curl -v "http://localhost:8000/islandora/rest/v1/object/your:pid"`

where 'your:pid' is the PID of an object that you should be denied access to based on your condition. Your curl request should return a 401.

**Comment by mjordan** [comment]
Some [recent changes](https://github.com/discoverygarden/islandora_rest/commit/8ccaa23af7c4b8d6a84f6079dc216b51b4fea475) to Islandora REST may make this fix unnecessary.

**Comment by MarcusBarnes** [comment]
Given the changes to Islandora REST, is it reasonable to require people who use Islandora REST to update that module should they start using Islandora Context?   I've tested using using the instructions in https://github.com/mjordan/islandora_context/issues/24#issuecomment-258451075 within an environment that doesn't have Islandora REST installed.  I got the access denied message as expected, but also the following notice:

```
Notice: Undefined offset: 1 in IslandoraContextReactionRestrictByIp->check_ip() (line 114 of /var/www/drupal/sites/all/modules/islandora_context/plugins/islandora_context_reaction_restrict_by_ip.inc).
```

**Comment by mjordan** [comment]
I think it's completely reasonable to require the latest version of Islandora REST (or at least a minimum version). I'll test with that version and also investigate the PHP notice.

**Comment by MarcusBarnes** [comment]
Thanks.  I was thinking that requiring an update to Islandora REST would simply the workaround for those who have Islandora Context installed but not Islandora REST.

**Comment by MarcusBarnes** [comment]
This [answer](http://stackoverflow.com/a/6576365/850828) provides a way to deal with the notices mentioned in  my [comment above](https://github.com/mjordan/islandora_context/issues/24#issuecomment-260997454).  See https://github.com/mjordan/islandora_context/blob/7.x/plugins/islandora_context_reaction_restrict_by_ip.inc#L114 for the bit of code that is generating the notice.  The notice is not related to the changes made in the issue-24 branch and it otherwise works as expected.  Would it be possible to merge the branch?

**Comment by mjordan** [comment]
Given that I haven't had a chance to test the effects that the new changes to the Islandora REST module have on this problem, maybe I can implement the fix for the notice that you link to in the previous comment. Would that be a good short-term action?

**Comment by MarcusBarnes** [comment]
That fix is only for the notice generated when using restrict by IP plugin - it's should be a separate github issue.  For a project I'm helping on that requires islandora_context, we don't require Islandora REST - the fix you have in the issue-24 branch works for us.

**Comment by mjordan** [comment]
OK, sorry - if you can open an issue for the notice fix, I'll work on it. I'm also happy to merge issue-24 now and then later take a look at the recent changes to Islandora REST.

**Comment by mjordan** [comment]
@MarcusBarnes just smoke tested issue-24 on our IP-restricted collection and it works as intended. Merged with 995ccbcbb60a4961e78618a787ff1d1609c73ed2.

**Comment by MarcusBarnes** [comment]
@mjordan As requested, I opened issue #30 to track work related to resolving the notice generated when using the restrict by IP plugin.  Thanks again for this awesome module!

**Comment by mjordan** [comment]
Thanks, closing this one.
