### ISSUE TITLE
Undefined offset notice when using restrict by IP plugin

### ISSUE THREAD

**Issue by MarcusBarnes** [SFULibrary/islandora_context#30]
When creating a context reaction using the restrict by IP plugin, the following notice is generated:
```
Notice: Undefined offset: 1 in IslandoraContextReactionRestrictByIp->check_ip() (line 114 of /var/www/drupal/sites/all/modules/islandora_context/plugins/islandora_context_reaction_restrict_by_ip.inc).
```
This [answer](http://stackoverflow.com/a/6576365/850828) provides a way to deal the code that is generating the notice.

**Comment by mjordan** [comment]
@MarcusBarnes would you mind posting the value of the "Allowed IP ranges" field in your reaction (with fake IPs if you want) that is triggering this notice, or send the real ones to me via email?

**Comment by MarcusBarnes** [comment]
@mjordan Sent you some details via Skype messaging.

**Comment by MarcusBarnes** [comment]
This error appears should the user not provide an IP range as expected, but rather just a single IP.
