### ISSUE TITLE
iTQL is dead, use Sparql instead

### ISSUE THREAD

**Issue by whikloj** [SFULibrary/islandora_context#33]
We've moved to using an external Blazegraph triplestore and the Smithsonian's trippi-sparql connector. Unfortunately this only allows us to use Sparql queries. 
Therefore queries [like this](https://github.com/mjordan/islandora_context/blob/ba7cf36d9696c0402a86a15dfafa3ce4008b3f4e/plugins/islandora_context_condition_collection_member.inc#L95) cause Exceptions and these occur even when the context you are accessing is not using the plugin.
I had to uninstall islandora_context to edit an existing context that was just using Path.

**Comment by mjordan** [comment]
Hm, not good. Running that query if the plugin is not active is definitely a bug, but it would be great to replace all itql queries with proper SPARQL queries.

**Comment by mjordan** [comment]
Maybe replace the offending function with https://github.com/Islandora/islandora_solution_pack_collection/blob/7.x/includes/utilities.inc#L210, at the risk of introducing a dependency on the Basic Collection SP?

**Comment by whikloj** [comment]
You could try that, as I said I haven't used this context so I'm not sure what the interface is. If you get all collections and provide checkboxes that might not save you anything, but if you are doing a search box you could reuse that code.

**Comment by mjordan** [comment]
If you've already got the SPARQL done, let's go with that. I'll give it a quick test here before merging if that's OK just to make sure there's no backwards breakage. Thanks!

**Comment by mjordan** [comment]
Smoke test passes, will merge. Thanks for catching and fixing this @whikloj !
