### ISSUE TITLE
Description does not show up for collections

### ISSUE THREAD

**Issue by nate-rcl** [SFULibrary/islandora_context#36]
1.  Add description to collection
2. Go to collection solution pack administration
3. Uncheck hide description
4. Go to collection - description not shown

**Comment by mjordan** [comment]
@nate-rcl what Context condition and/or reaction are you using?

**Comment by nate-rcl** [comment]
@mjordan

We have installed the islandora solution pack and then set Islandora Metadata display to "Islandora Solr Metadata managed by the Islandora Context module" which was previously set to "Islandora Solr Metadata"  

I then go to the islandora collection solution pack and scroll down to METADATA DISPLAY and check "Display object metadata".  

It gives me the option to hide and display Object Content, Field Set Metadata, In Collection and Description.  They all work except Description.  

I have not yet made any other configuration changes with the context module yet.

**Comment by nate-rcl** [comment]
@mjordan I made a pull request that fixed it for our install

**Comment by mjordan** [comment]
PR #37 merged.

**Comment by bencomp** [comment]
It looks like PR #37 is a reversal of the solution for issue #7. I've been looking into this as we're experiencing something very similar to what @bradspry was experiencing, only for the metadata fields display. I'll open another issue for that, but this reversal got my attention when looking into how #7 was solved.

**Comment by mjordan** [comment]
@bencomp please do, I'll take a look over the weekend.

**Comment by mjordan** [comment]
@bencomp you are correct, it does appear that PR #37 reverses changes made for issue #7. Sorry about that. I'm going to see if the fix for #7 solves your problem.
