### ISSUE TITLE
A description shows up even when it is not set in solr metadata

### ISSUE THREAD

**Issue by nate-rcl** [SFULibrary/islandora_context#38]
It looks like for the islandora_context_solr_metadata_description_callback the method must return false for collection models (islandora:collectionCModel) and an empty string for other objects.

**Comment by mjordan** [comment]
@nate-rcl is this still an issue, after the resolution of #48?

**Comment by mjordan** [comment]
@nate-rcl mind if I close this?

**Comment by nate-rcl** [comment]
@mjordan not at all - sounds good!
