### ISSUE TITLE
Add PID to collection list when setting collection membership condition

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_context#45]
Currently, when setting the "collection membership" condition, Context provides a list of collections that can be selected. This only presents the collection label, which may be ambiguous. Preferably the label would also include the collection PID (in parenthesis) next to the label, making it easier to work with.

**Comment by bondjimbond** [comment]
Also: what determines the ordering of collections in this list?

**Comment by mjordan** [comment]
The list is generated by a SPARQL query which is unsorted, so whatever the default sort order is for SPARQL/the Resource Index is what we get. How would you like to see it sorted, alpha by collection name?

**Comment by mjordan** [comment]
@bondjimbond I've added the PID and sorted by collection title/label. Please take a look. If you're thinking about another sort, let me know. Can you test the issue-45 branch by creating a new context using collection memebership? You may need to clear your cache first.

**Comment by bondjimbond** [comment]
Checked out the branch, works nicely for me. Thanks!

My preferred sort - I'd actually lean toward alphabetical sorting by PID, which would group namespaces and give you alpha sort on the collection ID (which is typically alpha anyway). But someone who uses namespaces differently from my multisite context might have a different opinion.

**Comment by mjordan** [comment]
Thanks for testing. Assuming that most sites aren't multisite, and knowing that I'm lazy, I'd like to leave the sorting as is, by title. That OK? If so, I'll merge now.

**Comment by bondjimbond** [comment]
Laziness is powerful. I can accept that. 👍

**Comment by mjordan** [comment]
Great, thanks. Merged with a807a0c3b3006a88c65f6d3fc304abcc688fe9af.
