### ISSUE TITLE
Solr Metadata display profile ignored in active context, falls back to DC metadata display

### ISSUE THREAD

**Issue by bencomp** [SFULibrary/islandora_context#48]
We installed Islandora Context to enable using a different Solr metadata display configuration for posters (Large Image objects) in a particular collection than for large image object in all other collections. We have separate MODS-based display configurations for all content models and before installing Islandora Context (IC), each configuration was associated with its corresponding content model(s).

Then, we:
1. installed IC, its dependencies
2. created a metadata display configuration for the poster collection
3. created a context triggered by the content model and collection for the poster collection
4. let IC manage the Solr metadata display

It worked! But then we found that objects that do not trigger the context (i.e. all except the posters) do not show their metadata using the previously associated display configuration. Although the IC readme is not explicit about this, it makes sense to me that when no context is active, the display configuration is undefined and the fall-back is used.

However, – and here's the issue – when I do define a context that triggers for other large image objects (the debug line shows that it actually triggers), it does not appear to use the display configuration that I want it to use. As in #7, but for the list of metadata fields, it shows a full list of DC fields instead of the non-empty MODS fields that we configured. Non-empty, because *Omit Empty Values* is checked on the *General Configuration* tab of `admin/islandora/search/islandora_solr/metadata`.

**Comment by mjordan** [comment]
@bencomp thank you for catching this. I will investigate this weekend.

**Comment by mjordan** [comment]
@bencomp can you test the issue-48 branch? If it works for you, I am going to ask @bradspry to test to confirm that #7 has not returned from the dead, and @nate-rcl to ensure that #36 has also not returned, zombie-like, and that #38 is not longer a problem.

**Comment by bencomp** [comment]
@mjordan this appears to work like a charm 😄 I hope it (still) works for the others too.

I see the metadata for the posters within the context as expected, for objects in the other context too and objects that trigger no contexts to be active use their associated Solr metadata configuration. I guess I can get rid of the 'fallback' context for large image objects that are not posters.

**Comment by mjordan** [comment]
Super, I am glad to hear that. @bradspry and @nate-rcl I'd like to go with this approach, which falls back to Solr Metadata's configuration if a context is not active. Can you test the issue-48 branch? If no issues arise I'd like to merge this on Monday, before I go on vacation.

**Comment by nate-rcl** [comment]
@mjordan I'm not going to get a chance to test by monday - but I'd say go ahead and merge - I'll test the released version when I get a chance.

**Comment by mjordan** [comment]
OK, thanks very much. I'll wait to see if @bradspry is cool with merging.

**Comment by mjordan** [comment]
@bradspry I'd love to merge this, but since you've got some skin the in the game it would be great if you could give it a quick smoketest.

**Comment by mjordan** [comment]
Closed with 733cc4301f06ec944987e78e82a7922ee8bf6ded.
