### ISSUE TITLE
SOLR metadata caching issue when 'context_ui' blocks set to default '1' (cache per role)

### ISSUE THREAD

**Issue by bradspry** [SFULibrary/islandora_context#5]
Witnessed a caching issue between objects when using a SOLR Metadata reaction: the same metadata was appearing on two different objects... and the metadata datastreams were truly different.

I had previously encountered a similar caching issue with Compound Object blocks, and solved it by setting the blocks not be cached.   

In Drupal's 'block' table, I went looking for 'context' blocks, and sure enough, their caching was set to '1' (cache per role).    I set all four 'context_ui' blocks to '-1' (do not cache).

drush cc all'ed, and the metadata issue went away.

Block "cache per role" is deadly for dynamic blocks...

**Comment by bradspry** [comment]
<pre>
Here's a detailed breakdown of what I touched in the process of eliminating cache issue:
1. In Drupal's 'cache' table, I found an entry for 'context'.   The expire value for the entry was set to '0' (never expire).   I noted a islandora_solr related entry in the table, with a value set to '-1'.   Thinking that '-1' indicated "never cache", I set the context cache entry to '-1'.  

After changing the setting, I 'drush cc all'ed and observed no effect on the solr metadata caching issue (no solution).

In looking at the 'cache' table today, I see neither of the aforementioned things (context and solr) have entries.
1. In Drupal's performance settings, I turned "Cache blocks" completely off.

After changing the setting, I 'drush cc all'ed and observed no effect on the solr metadata caching issue (no solution).
1. In Drupal's 'block' table, I went looking for 'context' blocks, found them, their caching was set to '1' (cache per role). I set all four 'context_ui' blocks I found to '-1' (do not cache).

After changing the settings, I 'drush cc all'ed and observed a profound effect on the solr metadata caching issue (SOLUTION).

<B
<pre>

**Comment by mjordan** [comment]
@bradspry I'm at another conference right now so can't take a detailed look at this issue until next week, but your thorough troubleshooting and testing will prove invaluable. Thanks!

**Comment by mjordan** [comment]
@bradspry I'm probably missing something, but the 'context_ui' blocks are only used to configure the contexts, they are not in play when end users view the output of a context reaction. You can disable the context_ui module and contexts still work. You say that "I set all four 'context_ui' blocks I found to '-1' (do not cache)" -- did you also set the 'context' blocks to -1? If not, I am wondering whether simply disabling the context_ui module would achieve the same effect as setting that module's blocks to -1.

Additionally, I'm not clear on where blocks come into play at all. Are you rendering the output of the Solr Metadata reaction in a block?

**Comment by bradspry** [comment]
Unable to reproduce today...

I set the 'context_ui' blocks back to '1' (cache per role), even enabled context's 'debug' setting; I still was unable to reproduce the issue...

I absolutely originally saw it, so did my metadata librarian, he spotted it before me...  The effect was:
1. Load a object containing islandora_context SOLR reaction
2. Load a second object containing the same islandora_context SOLR reaction (SOLR metadata from the first loaded record appeared on the second loaded record...)

It absolutely was a block cache by role anomaly, because the issue went away once I set 'context_ui's blocks to no cache (-1).

Don't know what else to say...

Except... The only difference between today's experiment and the original was I didn't touch "Cache blocks" in Drupal's performance settings today, it remained in the completely off position today.

Thank you for your time @mjordan

**Comment by mjordan** [comment]
Thanks for the update. If you set "Cache blocks" in the performance settings, can you replicate then?

I'll test on my end as well, now that you have narrowed down the problem so specifically.

**Comment by mjordan** [comment]
Just did some testing (as the admin user) and I can't replicate the cached metadata display on my dev laptop copy. `cache  from block where module = 'context_ui';` shows 1 for all rows, "Cache blocks" in Configuration > Performance is on, and I have a context that checks for both content model and collection membership whose reaction is to display a specific Solr metadata display viewer. I viewed about a dozen different objects that the context would apply to and verified that their metadata display showed the correct metadata.

@bradspry please keep an eye on this since I want to make sure that Islandora Context produces no side effects. Mind if I close this for now and we can reopen if necessary?

**Comment by bradspry** [comment]
@mjordan I will keep an eye on this, I'm sorry I failed to take a snapshot (drush vget) of all of the variables in play at the time of the anomaly...

Please close this issue for now; it can serve as landing place if anyone experiences the issue.

<B

**Comment by mjordan** [comment]
No problem. If you saw it once, it happened, so I suspect that the issue will come up again. Closing for now.
