### ISSUE TITLE
"Is Islandora Object check" is too generic and triggers in wrong situations

### ISSUE THREAD

**Issue by DiegoPino** [SFULibrary/islandora_context#52]
Problem:

https://github.com/SFULibrary/islandora_context/blob/f75ac720a4d8252a50bef6b542e73887cb6eaed1/plugins/islandora_context_condition_is_islandora_object.inc#L74

Which is the first check for an Islandora Object only checks if what is passed is an actual PHP object (any) and if there is an ::id property. Sadly that matches a wide scope of PHP Object Oriented situations.

Correct approach would be to  get the class of the Object and match it against the islandora_object class definition,  via `instanceof`AbstractFedoraObject (not getClass). Assuming any Abstract Object has properties like relationships will brake systems extending Fedora Objects or just creating Objects for its own internal use

Other option would be top wrap every member method call in a try/catch, but seems more perfomant to check for the class. 

This was reported by Katie Romabiles

**Comment by DiegoPino** [comment]
Some updates on this. Where i could reproduce the issue,  it seems to be the derivative alter hook which is used to accumulate possible hooks for an object in our module and other too. The alter hook context here is different to what i was expecting, since it runs reaction in the same place too.

https://github.com/SFULibrary/islandora_context/blob/7.x/islandora_context.module#L570-L613

I think i will simply exclude this modules derivative alter from any further processing and apply a workaround on our system to this issue. A simple blacklisting of this hook: islandora_context_islandora_derivative_alter should work out. Thanks

**Comment by DiegoPino** [comment]
Closing since i did not get any feedback. We solved this on our side. thanks

**Comment by mjordan** [comment]
Sorry @DiegoPino I've been traveling for the last two weeks. Can you provide some additional information on what condition triggered this error? Would a simple check for `is_a()` against a `FedoraObject` be more specific?

**Comment by DiegoPino** [comment]
@mjordan no worries. Its a general islandora desing issue (sadly). We assume every time we pass an Islandora Object around, that its a full Islandora Object but we require and ask for an Abstract Object only. Abstract Objects, as defined in Tuque don't need to have models or RELS-EXT at all. WE depend a lot on OO class inheritance to allow a generic, in memory only Abstract Object to be created to "harvest" all possible derivatives for a certain CMODEL and expose the options to the final user. That FakeObject is 100% an Abstract Object, but 99% of the Islandora code assume every Abstract Object is in fact a FedoraObject.. which is a higher level derived class based Object... No fix really. We ended faking relationships and CMODELs on our fakeObject, just to spare a tuque call and an extra fedora interaction to fix this. Its not 100% definitive 100% cover-all fix, but covers right now all the implemented use cases and allows people to use Context + IMI at the same time without issues now.

Whole mess is just a design bug of Islandora that has been replicated since tuque was born (in the early times of everything =)

Our fix is here in case you wonder

https://github.com/mnylc/islandora_multi_importer/pull/91/files

Thanks

**Comment by mjordan** [comment]
OK, thanks for the explanation. I'm happy to add  a check for a couple of other properties that might not be so common, like `->owner` and `->logMessage`, to provide a better check.

**Comment by DiegoPino** [comment]
Would really appreciate that, thanks. Any other method you can think of/relay on Context i should fake? Thanks a lot
