### ISSUE TITLE
Add a reaction to hide "In collections"

### ISSUE THREAD

**Issue by mjordan** [SFULibrary/islandora_context#53]
Good idea, we already can hide the description. Thread at https://groups.google.com/d/msg/islandora/BsIys6arL7o/8u2EoAkfBQAJ.

**Comment by mjordan** [comment]
Fixed with f20c8ff98285af1494be08b594c48daba9524b0e.

**Comment by pgmccann** [comment]
Hi, I've just installed islandora_context specifically for this rule. I found that it didn't work for Large Images - adding the following to the JS function sorted it:

```JavaScript
    $("div.islandora-large-image-metadata div h2").hide();
    $("div.islandora-large-image-metadata div ul li").hide();
```

I'll look into some other Content Types when I get the chance.

**Comment by mjordan** [comment]
@pgmccann that would be awesome. As you have discovered, the markup that this reaction hides varies across solution packs, and I have to admit that I don't often test with every solution pack. If you want to open a pull request I'll test and merge it.

Thanks for using (and debugging) Islandora Context!
