### ISSUE TITLE
Plugin "islandora_context_reaction_display_solr_metadata_description.inc" doesn't Omit Empty Values, displays dc.description instead

### ISSUE THREAD

**Issue by bradspry** [SFULibrary/islandora_context#7]
Example:
1. "Omit Empty Values" is checked in islandora_solr_metadata:
admin/islandora/search/islandora_solr/metadata
1. If metadata display config has "mods_abstract_ms" defined as description field

What is supposed to display:
Nothing, because "Omit Empty Values" is checked in islandora_solr_metadata

What is being displayed:
Islandora Context is seemingly ignoring "Omit Empty Values" and displaying dc.description instead

Screencast demonstration of Issue:
http://screencast.com/t/x3mB8B2un0r

**Comment by mjordan** [comment]
Thanks, will investigate.

**Comment by mjordan** [comment]
@bradspry working on this. Can replicate issue, but no positive results yet.

**Comment by mjordan** [comment]
@bradspry I'm afraid this one has gotten the better of me. I simply cannot figure out why this is happening.

**Comment by bradspry** [comment]
@mjordan, here is an updated analysis, with more detail than ever before:
http://screencast.com/t/7hwKIYjTR

If an object's metadata does not contain data in the defined islandora_solr_metadata/config description field, Islandora Context completely fails over to Islandora's core DC display function:
islandora/theme/islandora-dublin-core-description.tpl.php

From the screencast:

Object that doesn't contain mods.abstract data, which fails over to Islandora's core DC display:
https://island1.uncc.edu/islandora/object/motorsports%3A2189

Object with mods.abstract data, which is working properly:
https://island1.uncc.edu/islandora/object/motorsports%3A2365

<B

**Comment by mjordan** [comment]
@bradspry thanks for the tip. I'll take another look at this when I return from vacation next week.

**Comment by mjordan** [comment]
@bradspry can you test the issue-7 branch?

**Comment by bradspry** [comment]
@mjordan Setting up test now.

**Comment by bradspry** [comment]
@mjordan Apparently it works like a charm!

Below is a previously affected object; it was completely failing over to dc:description.  

With the issue-7 branch code applied, no description whatsoever is displayed:
https://island1.uncc.edu/islandora/object/motorsports%3A2189

That's exactly how we expect it to work!  issue-7 branch did the trick!

We will continue to test today and let you know if we see any issues!

We cannot thank you enough!   I need to make a pilgrimage to SFU just to shake your hand!  :clap: :clap: :clap: :v:

**Comment by mjordan** [comment]
Frickin' saweeet. Report back when you've finished testing and I'll merge issue-7 into 7.x.

**Comment by bradspry** [comment]
@mjordan More testing:

Object with no mods.abstract, no description whatsoever displays:
https://island1.uncc.edu/islandora/object/motorsports%3A5367

Object with mods.abstract data, description displays:
https://island1.uncc.edu/islandora/object/motorsports%3A5422

It is working really great!    My recommendation is to merge 👍 👍 

Thank You Again!!!

**Comment by mjordan** [comment]
Merged!
