### ISSUE TITLE
Add solr metadata configuration support for islandora_solution_pack_entities

### ISSUE THREAD

**Issue by bradspry** [SFULibrary/islandora_context#9]
Context does not successfully apply defined solr metadata configuration to islandora:personCModel objects.

Conditions are successful, however triggers for solr metadata configuration do not work as expected.

**Comment by bradspry** [comment]
@mjordan, I discovered the source of the problem today, and it's not islandora_context...    

Metadata display is set to "display:none" in [islandora_solution_pack_entities' islandora-person.css](https://github.com/Islandora/islandora_solution_pack_entities/blob/7.x/css/islandora-person.css#L47-L49) :weary:

**Comment by mjordan** [comment]
OK, thanks for letting me know.
